"""Task registration for the standalone HopperTrex MjLab package."""

from mjlab.tasks.registry import register_mjlab_task

from .agents import hoppertrex_balance_ppo_runner_cfg
from .hoppertrex_balance_task import (
  SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE,
  make_hoppertrex_balance_env_cfg,
)

HOPPERTREX_BALANCE_TASK_ID = "Mjlab-HopperTrex-Balance-v0"
HOPPERTREX_BALANCE_ROBUST_TASK_ID = "Mjlab-HopperTrex-Balance-Robust-v0"
HOPPERTREX_BALANCE_ROBUST_L2_TASK_ID = "Mjlab-HopperTrex-Balance-Robust-L2-v0"
HOPPERTREX_BALANCE_PUSH_L3_TASK_ID = "Mjlab-HopperTrex-Balance-Push-L3-v0"
HOPPERTREX_BALANCE_SLOW_SPEED_TASK_ID = "Mjlab-HopperTrex-Balance-SlowSpeed-v0"
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_LIN_SIGN_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-LinSign-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-LinSign-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_OBS_SCALE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-LinSign-ObsScale-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_FORWARD_ONLY_LIN_SIGN_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-ForwardOnly-LinSign-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-BackwardOnly-LinSign-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_FORWARD_ONLY_LIN_SIGN_OBS_SCALE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-ForwardOnly-LinSign-ObsScale-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-BackwardOnly-LinSign-ObsScale-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-BackwardOnly-LinSign-ObsScale-Strict-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_FEEDFORWARD_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-BackwardOnly-LinSign-ObsScale-Strict-Feedforward-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_FEEDFORWARD_LOW_RESIDUAL_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-BackwardOnly-LinSign-ObsScale-Strict-Feedforward-LowResidual-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_PITCH_TARGET_POS_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-BackwardOnly-LinSign-ObsScale-Strict-PitchTargetPos-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_PITCH_TARGET_NEG_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-BackwardOnly-LinSign-ObsScale-Strict-PitchTargetNeg-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_LEG_ASSIST_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-LinSign-LegAssist-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_LEG_ASSIST_SAFE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeed-Easy-LinSign-LegAssistSafe-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-Safe-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-Smooth-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_V2_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-SmoothV2-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_WHEEL_RATE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-Smooth-WheelRate-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_LOW_FORWARD_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-Smooth-LowForward-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_MID_FORWARD_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-Smooth-MidForward-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_MID_FORWARD_STABLE_RATE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-Smooth-MidForward-StableRate-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_MID_FORWARD_SLEW6_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale3-Smooth-MidForward-Slew6-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_MID_FORWARD_SLEW6_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale2p5-Smooth-MidForward-Slew6-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_MID_FORWARD_SLEW6_PUSH_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale2p5-Smooth-MidForward-Slew6-Push-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_BIDIR_SLEW6_PUSH_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale2p5-Smooth-Bidir-Slew6-Push-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_BIDIR_SLEW6_PUSH_LIN_SIGN_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale2p5-Smooth-Bidir-Slew6-Push-LinSign-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_BIDIR_LOW_YAW_SLEW6_LIN_SIGN_STRONG_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale2p5-Smooth-Bidir-LowYaw-Slew6-LinSignStrong-v0"
)
HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_MID_FORWARD_SLEW6_VAR_YAW_NO_BACK_TASK_ID = (
  "Mjlab-HopperTrex-Balance-SlowSpeedTurn-Sign-ObsScale-SafeV2-YawScale2p5-Smooth-MidForward-Slew6-VarYawNoBack-v0"
)
HOPPERTREX_BALANCE_TURN_L4_TASK_ID = "Mjlab-HopperTrex-Balance-Turn-L4-v0"
HOPPERTREX_BALANCE_TURN_L4_TRACK_TASK_ID = (
  "Mjlab-HopperTrex-Balance-Turn-L4-Track-v0"
)
HOPPERTREX_BALANCE_TURN_L4_TRACK_V2_TASK_ID = (
  "Mjlab-HopperTrex-Balance-Turn-L4-Track-v2"
)
HOPPERTREX_BALANCE_TURN_L4_EASY_TASK_ID = (
  "Mjlab-HopperTrex-Balance-Turn-L4-Easy-v0"
)
HOPPERTREX_BALANCE_TURN_L4_EASY_LOW_YAW_SCALE_TASK_ID = (
  "Mjlab-HopperTrex-Balance-Turn-L4-Easy-LowYawScale-v0"
)
HOPPERTREX_BALANCE_TURN_L4_SIGN_YAW_TASK_ID = (
  "Mjlab-HopperTrex-Balance-Turn-L4-SignYaw-v0"
)
HOPPERTREX_SCRATCH_STAGE0_BALANCE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage0-Balance-v0"
)
HOPPERTREX_SCRATCH_STAGE0_BALANCE_STABLE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage0-BalanceStable-v0"
)
HOPPERTREX_SCRATCH_STAGE1_SMALL_FORWARD_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-SmallForward-v0"
)
HOPPERTREX_SCRATCH_STAGE1_SMALL_FORWARD_STABLE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-SmallForwardStable-v0"
)
HOPPERTREX_SCRATCH_STAGE1_CLEAR_FORWARD_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ClearForward-v0"
)
HOPPERTREX_SCRATCH_STAGE1_FORWARD_ONLY_CLEAR_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ForwardOnlyClear-v0"
)
HOPPERTREX_SCRATCH_STAGE1_FORWARD_NOSPIKE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ForwardNoSpike-v0"
)
HOPPERTREX_SCRATCH_STAGE1_FORWARD_NOSPIKE_STRONG_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ForwardNoSpikeStrong-v0"
)
HOPPERTREX_SCRATCH_STAGE1_FORWARD_SMOOTH_SLEW12_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ForwardSmoothSlew12-v0"
)
HOPPERTREX_SCRATCH_STAGE1_FORWARD_SMOOTH_SLEW12_NOREV_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ForwardSmoothSlew12NoReverse-v0"
)
HOPPERTREX_SCRATCH_STAGE1_FORWARD_GUARDED_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ForwardGuarded-v0"
)
HOPPERTREX_SCRATCH_STAGE1_FORWARD_SUPPORT_GUARDED_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-ForwardSupportGuarded-v0"
)
HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-GentleForward-v0"
)
HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_SLEW6_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-GentleForwardSlew6-v0"
)
HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_ZERO_HOLD_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-GentleForwardZeroHold-v0"
)
HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_PITCH_TARGET_POS_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-GentleForwardPitchTargetPos-v0"
)
HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_PITCH_TARGET_NEG_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage1-GentleForwardPitchTargetNeg-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLin-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew12-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_LONG_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew12Long-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_SUSTAINED_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew12Sustained-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_SUSTAINED_NO_WHEEL_POS_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew12SustainedNoWheelPos-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6Band-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_DELTA_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6BandDelta-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_OVER8_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6BandOver8-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_DELTA_OVER8_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6BandDeltaOver8-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_NORM_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6Norm-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_NORM_ACC_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6NormAcc-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_REWARD_BALANCE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6RewardBalance-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_REWARD_BALANCE_TIGHT_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6RewardBalanceTight-v0"
)
HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_REWARD_BALANCE_FF_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage2-BidirLinSmoothSlew6RewardBalanceFF-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnly-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyMedium-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyMediumAligned-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_LITE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyMediumAlignedLite-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_SMOOTH_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyMediumAlignedSmooth-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_NARROW_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyMediumAlignedNarrow-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_ANTIPULSE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyMediumAlignedAntiPulse-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_ANTIPULSE_V2_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyMediumAlignedAntiPulseV2-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_TRACK_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyTrack-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_TRACK_V2_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyTrackV2-v0"
)
HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_STRONG_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage3-YawOnlyStrong-v0"
)
HOPPERTREX_SCRATCH_STAGE4_SMALL_LIN_SMALL_YAW_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage4-SmallLinSmallYaw-v0"
)
HOPPERTREX_SCRATCH_STAGE5_FULL_LIN_FULL_YAW_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage5-FullLinFullYaw-v0"
)
HOPPERTREX_SCRATCH_STAGE6_PUSH_NOISE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage6-PushNoise-v0"
)
HOPPERTREX_SCRATCH_STAGE8_LEG_ASSIST_SAFE_TASK_ID = (
  "Mjlab-HopperTrex-Scratch-Stage8-LegAssistSafe-v0"
)


def _register(
  task_id: str,
  robust: bool = False,
  robust_level: int = 1,
  push_l3: bool = False,
  slow_speed: bool = False,
  speed_level: int = 1,
  slow_speed_lin_sign: bool = False,
  slow_speed_obs_scale: bool = False,
  slow_speed_forward_only: bool = False,
  slow_speed_backward_only: bool = False,
  slow_speed_backward_strict: bool = False,
  slow_speed_command_feedforward: bool = False,
  slow_speed_command_feedforward_low_residual: bool = False,
  slow_speed_pitch_target_pos: bool = False,
  slow_speed_pitch_target_neg: bool = False,
  limited_leg_assist: bool = False,
  limited_leg_assist_safe: bool = False,
  slow_speed_turn: bool = False,
  slow_speed_turn_sign: bool = False,
  slow_speed_turn_obs_scale: bool = False,
  slow_speed_turn_safe: bool = False,
  slow_speed_turn_safe_v2: bool = False,
  slow_speed_turn_safe_v2_yaw_scale3: bool = False,
  slow_speed_turn_safe_v2_yaw_scale2p5: bool = False,
  slow_speed_turn_safe_v2_yaw_smooth: bool = False,
  slow_speed_turn_safe_v2_yaw_smooth_v2: bool = False,
  slow_speed_turn_safe_v2_wheel_rate: bool = False,
  slow_speed_turn_low_forward: bool = False,
  slow_speed_turn_mid_forward: bool = False,
  slow_speed_turn_bidirectional: bool = False,
  slow_speed_turn_bidirectional_low_yaw: bool = False,
  slow_speed_turn_bidirectional_lin_sign: bool = False,
  slow_speed_turn_bidirectional_lin_sign_strong: bool = False,
  slow_speed_turn_stable_rate: bool = False,
  slow_speed_turn_target_slew: bool = False,
  slow_speed_turn_variable_yaw: bool = False,
  slow_speed_turn_no_backward: bool = False,
  slow_speed_turn_push: bool = False,
  turn_l4: bool = False,
  turn_level: int = 1,
  scratch_stage0_stable: bool = False,
  scratch_stable_regularization: bool = False,
  scratch_stage1_clear_forward: bool = False,
  scratch_stage1_forward_only_clear: bool = False,
  scratch_stage1_forward_nospike: bool = False,
  scratch_stage1_forward_nospike_strong: bool = False,
  scratch_stage1_forward_smooth_slew12: bool = False,
  scratch_stage1_forward_smooth_slew12_norev: bool = False,
  scratch_stage2_bidir_smooth_slew12: bool = False,
  scratch_stage2_bidir_smooth_slew6_band: bool = False,
  scratch_stage2_bidir_smooth_slew6_band_delta: bool = False,
  scratch_stage2_bidir_smooth_slew6_band_over8: bool = False,
  scratch_stage2_bidir_smooth_slew6_band_delta_over8: bool = False,
  scratch_stage2_bidir_smooth_slew6_norm: bool = False,
  scratch_stage2_bidir_smooth_slew6_norm_acc: bool = False,
  scratch_stage2_bidir_smooth_slew6_reward_balance: bool = False,
  scratch_stage2_bidir_smooth_slew6_reward_balance_tight: bool = False,
  scratch_stage1_forward_guarded: bool = False,
  scratch_stage1_forward_support_guarded: bool = False,
  scratch_stage1_gentle_forward: bool = False,
  scratch_stage1_gentle_forward_slew6: bool = False,
  scratch_stage1_gentle_forward_zero_hold: bool = False,
  training_episode_length_s: float | None = None,
  command_resampling_time_range: tuple[float, float] = (5.0, 10.0),
  zero_wheel_joint_pos_obs: bool = False,
) -> None:
  is_scratch_stage3_yaw = (
    "Stage3-YawOnly" in task_id
    or "stage3-yaw-only" in task_id
  )
  if is_scratch_stage3_yaw and training_episode_length_s is None:
    training_episode_length_s = SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S
    command_resampling_time_range = (
      SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
    )

  register_mjlab_task(
    task_id=task_id,
    env_cfg=make_hoppertrex_balance_env_cfg(
      play=False,
      robust=robust,
      robust_level=robust_level,
      push_l3=push_l3,
      slow_speed=slow_speed,
      speed_level=speed_level,
      slow_speed_lin_sign=slow_speed_lin_sign,
      slow_speed_obs_scale=slow_speed_obs_scale,
      slow_speed_forward_only=slow_speed_forward_only,
      slow_speed_backward_only=slow_speed_backward_only,
      slow_speed_backward_strict=slow_speed_backward_strict,
      slow_speed_command_feedforward=slow_speed_command_feedforward,
      slow_speed_command_feedforward_low_residual=slow_speed_command_feedforward_low_residual,
      slow_speed_pitch_target_pos=slow_speed_pitch_target_pos,
      slow_speed_pitch_target_neg=slow_speed_pitch_target_neg,
      limited_leg_assist=limited_leg_assist,
      limited_leg_assist_safe=limited_leg_assist_safe,
      slow_speed_turn=slow_speed_turn,
      slow_speed_turn_sign=slow_speed_turn_sign,
      slow_speed_turn_obs_scale=slow_speed_turn_obs_scale,
      slow_speed_turn_safe=slow_speed_turn_safe,
      slow_speed_turn_safe_v2=slow_speed_turn_safe_v2,
      slow_speed_turn_safe_v2_yaw_scale3=slow_speed_turn_safe_v2_yaw_scale3,
      slow_speed_turn_safe_v2_yaw_scale2p5=slow_speed_turn_safe_v2_yaw_scale2p5,
      slow_speed_turn_safe_v2_yaw_smooth=slow_speed_turn_safe_v2_yaw_smooth,
      slow_speed_turn_safe_v2_yaw_smooth_v2=slow_speed_turn_safe_v2_yaw_smooth_v2,
      slow_speed_turn_safe_v2_wheel_rate=slow_speed_turn_safe_v2_wheel_rate,
      slow_speed_turn_low_forward=slow_speed_turn_low_forward,
      slow_speed_turn_mid_forward=slow_speed_turn_mid_forward,
      slow_speed_turn_bidirectional=slow_speed_turn_bidirectional,
      slow_speed_turn_bidirectional_low_yaw=slow_speed_turn_bidirectional_low_yaw,
      slow_speed_turn_bidirectional_lin_sign=slow_speed_turn_bidirectional_lin_sign,
      slow_speed_turn_bidirectional_lin_sign_strong=slow_speed_turn_bidirectional_lin_sign_strong,
      slow_speed_turn_stable_rate=slow_speed_turn_stable_rate,
      slow_speed_turn_target_slew=slow_speed_turn_target_slew,
      slow_speed_turn_variable_yaw=slow_speed_turn_variable_yaw,
      slow_speed_turn_no_backward=slow_speed_turn_no_backward,
      slow_speed_turn_push=slow_speed_turn_push,
      turn_l4=turn_l4,
      turn_level=turn_level,
      scratch_stage0_stable=scratch_stage0_stable,
      scratch_stable_regularization=scratch_stable_regularization,
      scratch_stage1_clear_forward=scratch_stage1_clear_forward,
      scratch_stage1_forward_only_clear=scratch_stage1_forward_only_clear,
      scratch_stage1_forward_nospike=scratch_stage1_forward_nospike,
      scratch_stage1_forward_nospike_strong=scratch_stage1_forward_nospike_strong,
      scratch_stage1_forward_smooth_slew12=scratch_stage1_forward_smooth_slew12,
      scratch_stage1_forward_smooth_slew12_norev=(
        scratch_stage1_forward_smooth_slew12_norev
      ),
      scratch_stage2_bidir_smooth_slew12=scratch_stage2_bidir_smooth_slew12,
      scratch_stage2_bidir_smooth_slew6_band=scratch_stage2_bidir_smooth_slew6_band,
      scratch_stage2_bidir_smooth_slew6_band_delta=(
        scratch_stage2_bidir_smooth_slew6_band_delta
      ),
      scratch_stage2_bidir_smooth_slew6_band_over8=(
        scratch_stage2_bidir_smooth_slew6_band_over8
      ),
      scratch_stage2_bidir_smooth_slew6_band_delta_over8=(
        scratch_stage2_bidir_smooth_slew6_band_delta_over8
      ),
      scratch_stage2_bidir_smooth_slew6_norm=scratch_stage2_bidir_smooth_slew6_norm,
      scratch_stage2_bidir_smooth_slew6_norm_acc=(
        scratch_stage2_bidir_smooth_slew6_norm_acc
      ),
      scratch_stage2_bidir_smooth_slew6_reward_balance=(
        scratch_stage2_bidir_smooth_slew6_reward_balance
      ),
      scratch_stage2_bidir_smooth_slew6_reward_balance_tight=(
        scratch_stage2_bidir_smooth_slew6_reward_balance_tight
      ),
      scratch_stage1_forward_guarded=scratch_stage1_forward_guarded,
      scratch_stage1_forward_support_guarded=scratch_stage1_forward_support_guarded,
      scratch_stage1_gentle_forward=scratch_stage1_gentle_forward,
      scratch_stage1_gentle_forward_slew6=scratch_stage1_gentle_forward_slew6,
      scratch_stage1_gentle_forward_zero_hold=scratch_stage1_gentle_forward_zero_hold,
      training_episode_length_s=training_episode_length_s,
      command_resampling_time_range=command_resampling_time_range,
      zero_wheel_joint_pos_obs=zero_wheel_joint_pos_obs,
    ),
    play_env_cfg=make_hoppertrex_balance_env_cfg(
      play=True,
      robust=robust,
      robust_level=robust_level,
      push_l3=push_l3,
      slow_speed=slow_speed,
      speed_level=speed_level,
      slow_speed_lin_sign=slow_speed_lin_sign,
      slow_speed_obs_scale=slow_speed_obs_scale,
      slow_speed_forward_only=slow_speed_forward_only,
      slow_speed_backward_only=slow_speed_backward_only,
      slow_speed_backward_strict=slow_speed_backward_strict,
      slow_speed_command_feedforward=slow_speed_command_feedforward,
      slow_speed_command_feedforward_low_residual=slow_speed_command_feedforward_low_residual,
      slow_speed_pitch_target_pos=slow_speed_pitch_target_pos,
      slow_speed_pitch_target_neg=slow_speed_pitch_target_neg,
      limited_leg_assist=limited_leg_assist,
      limited_leg_assist_safe=limited_leg_assist_safe,
      slow_speed_turn=slow_speed_turn,
      slow_speed_turn_sign=slow_speed_turn_sign,
      slow_speed_turn_obs_scale=slow_speed_turn_obs_scale,
      slow_speed_turn_safe=slow_speed_turn_safe,
      slow_speed_turn_safe_v2=slow_speed_turn_safe_v2,
      slow_speed_turn_safe_v2_yaw_scale3=slow_speed_turn_safe_v2_yaw_scale3,
      slow_speed_turn_safe_v2_yaw_scale2p5=slow_speed_turn_safe_v2_yaw_scale2p5,
      slow_speed_turn_safe_v2_yaw_smooth=slow_speed_turn_safe_v2_yaw_smooth,
      slow_speed_turn_safe_v2_yaw_smooth_v2=slow_speed_turn_safe_v2_yaw_smooth_v2,
      slow_speed_turn_safe_v2_wheel_rate=slow_speed_turn_safe_v2_wheel_rate,
      slow_speed_turn_low_forward=slow_speed_turn_low_forward,
      slow_speed_turn_mid_forward=slow_speed_turn_mid_forward,
      slow_speed_turn_bidirectional=slow_speed_turn_bidirectional,
      slow_speed_turn_bidirectional_low_yaw=slow_speed_turn_bidirectional_low_yaw,
      slow_speed_turn_bidirectional_lin_sign=slow_speed_turn_bidirectional_lin_sign,
      slow_speed_turn_bidirectional_lin_sign_strong=slow_speed_turn_bidirectional_lin_sign_strong,
      slow_speed_turn_stable_rate=slow_speed_turn_stable_rate,
      slow_speed_turn_target_slew=slow_speed_turn_target_slew,
      slow_speed_turn_variable_yaw=slow_speed_turn_variable_yaw,
      slow_speed_turn_no_backward=slow_speed_turn_no_backward,
      slow_speed_turn_push=slow_speed_turn_push,
      turn_l4=turn_l4,
      turn_level=turn_level,
      scratch_stage0_stable=scratch_stage0_stable,
      scratch_stable_regularization=scratch_stable_regularization,
      scratch_stage1_clear_forward=scratch_stage1_clear_forward,
      scratch_stage1_forward_only_clear=scratch_stage1_forward_only_clear,
      scratch_stage1_forward_nospike=scratch_stage1_forward_nospike,
      scratch_stage1_forward_nospike_strong=scratch_stage1_forward_nospike_strong,
      scratch_stage1_forward_smooth_slew12=scratch_stage1_forward_smooth_slew12,
      scratch_stage1_forward_smooth_slew12_norev=(
        scratch_stage1_forward_smooth_slew12_norev
      ),
      scratch_stage2_bidir_smooth_slew12=scratch_stage2_bidir_smooth_slew12,
      scratch_stage2_bidir_smooth_slew6_band=scratch_stage2_bidir_smooth_slew6_band,
      scratch_stage2_bidir_smooth_slew6_band_delta=(
        scratch_stage2_bidir_smooth_slew6_band_delta
      ),
      scratch_stage2_bidir_smooth_slew6_band_over8=(
        scratch_stage2_bidir_smooth_slew6_band_over8
      ),
      scratch_stage2_bidir_smooth_slew6_band_delta_over8=(
        scratch_stage2_bidir_smooth_slew6_band_delta_over8
      ),
      scratch_stage2_bidir_smooth_slew6_norm=scratch_stage2_bidir_smooth_slew6_norm,
      scratch_stage2_bidir_smooth_slew6_norm_acc=(
        scratch_stage2_bidir_smooth_slew6_norm_acc
      ),
      scratch_stage2_bidir_smooth_slew6_reward_balance=(
        scratch_stage2_bidir_smooth_slew6_reward_balance
      ),
      scratch_stage2_bidir_smooth_slew6_reward_balance_tight=(
        scratch_stage2_bidir_smooth_slew6_reward_balance_tight
      ),
      scratch_stage1_forward_guarded=scratch_stage1_forward_guarded,
      scratch_stage1_forward_support_guarded=scratch_stage1_forward_support_guarded,
      scratch_stage1_gentle_forward=scratch_stage1_gentle_forward,
      scratch_stage1_gentle_forward_slew6=scratch_stage1_gentle_forward_slew6,
      scratch_stage1_gentle_forward_zero_hold=scratch_stage1_gentle_forward_zero_hold,
      training_episode_length_s=training_episode_length_s,
      command_resampling_time_range=command_resampling_time_range,
      zero_wheel_joint_pos_obs=zero_wheel_joint_pos_obs,
    ),
    rl_cfg=hoppertrex_balance_ppo_runner_cfg(),
    runner_cls=None,
  )


_register(HOPPERTREX_BALANCE_TASK_ID)
_register("hoppertrex-balance-v0")
_register(HOPPERTREX_BALANCE_ROBUST_TASK_ID, robust=True)
_register("hoppertrex-balance-robust-v0", robust=True)
_register(HOPPERTREX_BALANCE_ROBUST_L2_TASK_ID, robust=True, robust_level=2)
_register("hoppertrex-balance-robust-l2-v0", robust=True, robust_level=2)
_register(
  HOPPERTREX_BALANCE_PUSH_L3_TASK_ID,
  robust=True,
  robust_level=2,
  push_l3=True,
)
_register(
  "hoppertrex-balance-push-l3-v0",
  robust=True,
  robust_level=2,
  push_l3=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
)
_register(
  "hoppertrex-balance-slow-speed-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
)
_register(
  "hoppertrex-balance-slow-speed-easy-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_LIN_SIGN_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  slow_speed_lin_sign=True,
)
_register(
  "hoppertrex-balance-slow-speed-lin-sign-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  slow_speed_lin_sign=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-lin-sign-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_OBS_SCALE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-lin-sign-obs-scale-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_FORWARD_ONLY_LIN_SIGN_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_forward_only=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-forward-only-lin-sign-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_forward_only=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_backward_only=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-backward-only-lin-sign-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_backward_only=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_FORWARD_ONLY_LIN_SIGN_OBS_SCALE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-forward-only-lin-sign-obs-scale-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-backward-only-lin-sign-obs-scale-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-backward-only-lin-sign-obs-scale-strict-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_PITCH_TARGET_POS_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_pitch_target_pos=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-backward-only-lin-sign-obs-scale-strict-pitch-target-pos-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_pitch_target_pos=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_PITCH_TARGET_NEG_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_pitch_target_neg=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-backward-only-lin-sign-obs-scale-strict-pitch-target-neg-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_pitch_target_neg=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_FEEDFORWARD_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_command_feedforward=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-backward-only-lin-sign-obs-scale-strict-feedforward-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_command_feedforward=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_BACKWARD_ONLY_LIN_SIGN_OBS_SCALE_STRICT_FEEDFORWARD_LOW_RESIDUAL_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_command_feedforward=True,
  slow_speed_command_feedforward_low_residual=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-backward-only-lin-sign-obs-scale-strict-feedforward-low-residual-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_backward_only=True,
  slow_speed_backward_strict=True,
  slow_speed_command_feedforward=True,
  slow_speed_command_feedforward_low_residual=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_LEG_ASSIST_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  limited_leg_assist=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-lin-sign-leg-assist-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  limited_leg_assist=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_EASY_LIN_SIGN_LEG_ASSIST_SAFE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  limited_leg_assist=True,
  limited_leg_assist_safe=True,
)
_register(
  "hoppertrex-balance-slow-speed-easy-lin-sign-leg-assist-safe-v0",
  robust=True,
  robust_level=2,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  limited_leg_assist=True,
  limited_leg_assist_safe=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-smooth-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_V2_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_safe_v2_yaw_smooth_v2=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-smooth-v2-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_safe_v2_yaw_smooth_v2=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_WHEEL_RATE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_safe_v2_wheel_rate=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-smooth-wheel-rate-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_safe_v2_wheel_rate=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_LOW_FORWARD_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_low_forward=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-smooth-low-forward-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_low_forward=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_MID_FORWARD_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-smooth-mid-forward-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_MID_FORWARD_STABLE_RATE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_stable_rate=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-smooth-mid-forward-stable-rate-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_stable_rate=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE3_SMOOTH_MID_FORWARD_SLEW6_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale3-smooth-mid-forward-slew6-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale3=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_MID_FORWARD_SLEW6_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale2p5-smooth-mid-forward-slew6-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_MID_FORWARD_SLEW6_PUSH_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale2p5-smooth-mid-forward-slew6-push-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_BIDIR_SLEW6_PUSH_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale2p5-smooth-bidir-slew6-push-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_BIDIR_SLEW6_PUSH_LIN_SIGN_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale2p5-smooth-bidir-slew6-push-lin-sign-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_BIDIR_LOW_YAW_SLEW6_LIN_SIGN_STRONG_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_low_yaw=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_bidirectional_lin_sign_strong=True,
  slow_speed_turn_target_slew=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale2p5-smooth-bidir-low-yaw-slew6-lin-sign-strong-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_low_yaw=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_bidirectional_lin_sign_strong=True,
  slow_speed_turn_target_slew=True,
)
_register(
  HOPPERTREX_BALANCE_SLOW_SPEED_TURN_SIGN_OBS_SCALE_SAFE_V2_YAW_SCALE2P5_SMOOTH_MID_FORWARD_SLEW6_VAR_YAW_NO_BACK_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_variable_yaw=True,
  slow_speed_turn_no_backward=True,
)
_register(
  "hoppertrex-balance-slow-speed-turn-sign-obs-scale-safe-v2-yaw-scale2p5-smooth-mid-forward-slew6-var-yaw-no-back-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_mid_forward=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_variable_yaw=True,
  slow_speed_turn_no_backward=True,
)
_register(
  HOPPERTREX_BALANCE_TURN_L4_TASK_ID,
  robust=True,
  robust_level=2,
  turn_l4=True,
)
_register(
  "hoppertrex-balance-turn-l4-v0",
  robust=True,
  robust_level=2,
  turn_l4=True,
)
_register(
  HOPPERTREX_BALANCE_TURN_L4_TRACK_TASK_ID,
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=2,
)
_register(
  "hoppertrex-balance-turn-l4-track-v0",
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=2,
)
_register(
  HOPPERTREX_BALANCE_TURN_L4_TRACK_V2_TASK_ID,
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=3,
)
_register(
  "hoppertrex-balance-turn-l4-track-v2",
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=3,
)
_register(
  HOPPERTREX_BALANCE_TURN_L4_EASY_TASK_ID,
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=4,
)
_register(
  "hoppertrex-balance-turn-l4-easy-v0",
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=4,
)
_register(
  HOPPERTREX_BALANCE_TURN_L4_EASY_LOW_YAW_SCALE_TASK_ID,
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=5,
)
_register(
  "hoppertrex-balance-turn-l4-easy-low-yaw-scale-v0",
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=5,
)
_register(
  HOPPERTREX_BALANCE_TURN_L4_SIGN_YAW_TASK_ID,
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=6,
)
_register(
  "hoppertrex-balance-turn-l4-sign-yaw-v0",
  robust=True,
  robust_level=2,
  turn_l4=True,
  turn_level=6,
)


# Scratch curriculum tasks: Stage 0 starts from random initialization. Stages 1-5
# keep reset/push disturbances off so command-learning failures are easier to
# attribute. Stage 6 intentionally adds reset disturbance and push.
_register(HOPPERTREX_SCRATCH_STAGE0_BALANCE_TASK_ID)
_register("hoppertrex-scratch-stage0-balance-v0")
_register(
  HOPPERTREX_SCRATCH_STAGE0_BALANCE_STABLE_TASK_ID,
  scratch_stage0_stable=True,
)
_register(
  "hoppertrex-scratch-stage0-balance-stable-v0",
  scratch_stage0_stable=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_SMALL_FORWARD_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
)
_register(
  "hoppertrex-scratch-stage1-small-forward-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_SMALL_FORWARD_STABLE_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stable_regularization=True,
)
_register(
  "hoppertrex-scratch-stage1-small-forward-stable-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stable_regularization=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_CLEAR_FORWARD_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_clear_forward=True,
)
_register(
  "hoppertrex-scratch-stage1-clear-forward-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_clear_forward=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_FORWARD_ONLY_CLEAR_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_only_clear=True,
)
_register(
  "hoppertrex-scratch-stage1-forward-only-clear-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_only_clear=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_FORWARD_NOSPIKE_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_nospike=True,
)
_register(
  "hoppertrex-scratch-stage1-forward-nospike-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_nospike=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_FORWARD_NOSPIKE_STRONG_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_nospike_strong=True,
)
_register(
  "hoppertrex-scratch-stage1-forward-nospike-strong-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_nospike_strong=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_FORWARD_SMOOTH_SLEW12_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_smooth_slew12=True,
)
_register(
  "hoppertrex-scratch-stage1-forward-smooth-slew12-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_smooth_slew12=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_FORWARD_SMOOTH_SLEW12_NOREV_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_smooth_slew12_norev=True,
)
_register(
  "hoppertrex-scratch-stage1-forward-smooth-slew12-noreverse-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_smooth_slew12_norev=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_FORWARD_GUARDED_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_guarded=True,
)
_register(
  "hoppertrex-scratch-stage1-forward-guarded-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_guarded=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_FORWARD_SUPPORT_GUARDED_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_support_guarded=True,
)
_register(
  "hoppertrex-scratch-stage1-forward-support-guarded-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_forward_support_guarded=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward=True,
)
_register(
  "hoppertrex-scratch-stage1-gentle-forward-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_SLEW6_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward_slew6=True,
)
_register(
  "hoppertrex-scratch-stage1-gentle-forward-slew6-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward_slew6=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_ZERO_HOLD_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward_zero_hold=True,
)
_register(
  "hoppertrex-scratch-stage1-gentle-forward-zero-hold-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward_zero_hold=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_PITCH_TARGET_POS_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward=True,
  slow_speed_pitch_target_pos=True,
)
_register(
  "hoppertrex-scratch-stage1-gentle-forward-pitch-target-pos-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward=True,
  slow_speed_pitch_target_pos=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE1_GENTLE_FORWARD_PITCH_TARGET_NEG_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward=True,
  slow_speed_pitch_target_neg=True,
)
_register(
  "hoppertrex-scratch-stage1-gentle-forward-pitch-target-neg-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_forward_only=True,
  scratch_stage1_gentle_forward=True,
  slow_speed_pitch_target_neg=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew12-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_LONG_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew12-long-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_SUSTAINED_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew12-sustained-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW12_SUSTAINED_NO_WHEEL_POS_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew12-sustained-no-wheel-pos-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew12=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-band-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_DELTA_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band_delta=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-band-delta-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band_delta=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_OVER8_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band_over8=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-band-over8-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band_over8=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_BAND_DELTA_OVER8_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band_delta_over8=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-band-delta-over8-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_band_delta_over8=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_NORM_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_norm=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-norm-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_norm=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_NORM_ACC_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_norm_acc=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-norm-acc-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_norm_acc=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_REWARD_BALANCE_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_reward_balance=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-reward-balance-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_reward_balance=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_REWARD_BALANCE_TIGHT_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_reward_balance_tight=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-reward-balance-tight-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  scratch_stage2_bidir_smooth_slew6_reward_balance_tight=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE2_BIDIR_LIN_SMOOTH_SLEW6_REWARD_BALANCE_FF_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_command_feedforward=True,
  slow_speed_command_feedforward_low_residual=True,
  scratch_stage2_bidir_smooth_slew6_reward_balance=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage2-bidir-lin-smooth-slew6-reward-balance-ff-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  slow_speed_command_feedforward=True,
  slow_speed_command_feedforward_low_residual=True,
  scratch_stage2_bidir_smooth_slew6_reward_balance=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_TASK_ID,
  turn_l4=True,
  turn_level=6,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-v0",
  turn_l4=True,
  turn_level=6,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_TASK_ID,
  turn_l4=True,
  turn_level=8,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-medium-v0",
  turn_l4=True,
  turn_level=8,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_TASK_ID,
  turn_l4=True,
  turn_level=11,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-medium-aligned-v0",
  turn_l4=True,
  turn_level=11,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_LITE_TASK_ID,
  turn_l4=True,
  turn_level=12,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-medium-aligned-lite-v0",
  turn_l4=True,
  turn_level=12,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_SMOOTH_TASK_ID,
  turn_l4=True,
  turn_level=13,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-medium-aligned-smooth-v0",
  turn_l4=True,
  turn_level=13,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_NARROW_TASK_ID,
  turn_l4=True,
  turn_level=14,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-medium-aligned-narrow-v0",
  turn_l4=True,
  turn_level=14,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_ANTIPULSE_TASK_ID,
  turn_l4=True,
  turn_level=15,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-medium-aligned-antipulse-v0",
  turn_l4=True,
  turn_level=15,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_MEDIUM_ALIGNED_ANTIPULSE_V2_TASK_ID,
  turn_l4=True,
  turn_level=16,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-medium-aligned-antipulse-v2-v0",
  turn_l4=True,
  turn_level=16,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_TRACK_TASK_ID,
  turn_l4=True,
  turn_level=9,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-track-v0",
  turn_l4=True,
  turn_level=9,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_TRACK_V2_TASK_ID,
  turn_l4=True,
  turn_level=10,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-track-v2-v0",
  turn_l4=True,
  turn_level=10,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE3_YAW_ONLY_STRONG_TASK_ID,
  turn_l4=True,
  turn_level=7,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage3-yaw-only-strong-v0",
  turn_l4=True,
  turn_level=7,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE4_SMALL_LIN_SMALL_YAW_TASK_ID,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_low_yaw=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_bidirectional_lin_sign_strong=True,
  slow_speed_turn_target_slew=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage4-small-lin-small-yaw-v0",
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_low_yaw=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_bidirectional_lin_sign_strong=True,
  slow_speed_turn_target_slew=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE5_FULL_LIN_FULL_YAW_TASK_ID,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_target_slew=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage5-full-lin-full-yaw-v0",
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_target_slew=True,
  training_episode_length_s=SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_LONG_EPISODE_S,
  command_resampling_time_range=(
    SCRATCH_STAGE2_BIDIR_SMOOTH_SLEW12_SUSTAINED_RESAMPLE_TIME_RANGE
  ),
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE6_PUSH_NOISE_TASK_ID,
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage6-push-noise-v0",
  robust=True,
  robust_level=2,
  slow_speed_turn=True,
  slow_speed_turn_sign=True,
  slow_speed_turn_obs_scale=True,
  slow_speed_turn_safe_v2=True,
  slow_speed_turn_safe_v2_yaw_scale2p5=True,
  slow_speed_turn_safe_v2_yaw_smooth=True,
  slow_speed_turn_bidirectional=True,
  slow_speed_turn_bidirectional_lin_sign=True,
  slow_speed_turn_target_slew=True,
  slow_speed_turn_push=True,
  zero_wheel_joint_pos_obs=True,
)
_register(
  HOPPERTREX_SCRATCH_STAGE8_LEG_ASSIST_SAFE_TASK_ID,
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  limited_leg_assist=True,
  limited_leg_assist_safe=True,
  zero_wheel_joint_pos_obs=True,
)
_register(
  "hoppertrex-scratch-stage8-leg-assist-safe-v0",
  slow_speed=True,
  speed_level=0,
  slow_speed_lin_sign=True,
  slow_speed_obs_scale=True,
  limited_leg_assist=True,
  limited_leg_assist_safe=True,
  zero_wheel_joint_pos_obs=True,
)
